package online.qsx.mapper;

import java.util.List;
import online.qsx.model.Result;
import online.qsx.model.ResultCriteria;
import org.apache.ibatis.annotations.Param;

public interface ResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table result
     *
     * @mbggenerated Sat Jan 13 15:50:48 CST 2018
     */
    int countByExample(ResultCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table result
     *
     * @mbggenerated Sat Jan 13 15:50:48 CST 2018
     */
    int deleteByExample(ResultCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table result
     *
     * @mbggenerated Sat Jan 13 15:50:48 CST 2018
     */
    int insert(Result record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table result
     *
     * @mbggenerated Sat Jan 13 15:50:48 CST 2018
     */
    int insertSelective(Result record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table result
     *
     * @mbggenerated Sat Jan 13 15:50:48 CST 2018
     */
    List<Result> selectByExample(ResultCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table result
     *
     * @mbggenerated Sat Jan 13 15:50:48 CST 2018
     */
    int updateByExampleSelective(@Param("record") Result record, @Param("example") ResultCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table result
     *
     * @mbggenerated Sat Jan 13 15:50:48 CST 2018
     */
    int updateByExample(@Param("record") Result record, @Param("example") ResultCriteria example);
}