package online.qsx.mapper;

import java.util.List;
import online.qsx.model.Subject;
import online.qsx.model.SubjectCriteria;
import org.apache.ibatis.annotations.Param;

public interface SubjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject
     *
     * @mbggenerated Sat Jan 13 15:50:48 CST 2018
     */
    int countByExample(SubjectCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject
     *
     * @mbggenerated Sat Jan 13 15:50:48 CST 2018
     */
    int deleteByExample(SubjectCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject
     *
     * @mbggenerated Sat Jan 13 15:50:48 CST 2018
     */
    int deleteByPrimaryKey(Integer subjectno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject
     *
     * @mbggenerated Sat Jan 13 15:50:48 CST 2018
     */
    int insert(Subject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject
     *
     * @mbggenerated Sat Jan 13 15:50:48 CST 2018
     */
    int insertSelective(Subject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject
     *
     * @mbggenerated Sat Jan 13 15:50:48 CST 2018
     */
    List<Subject> selectByExample(SubjectCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject
     *
     * @mbggenerated Sat Jan 13 15:50:48 CST 2018
     */
    Subject selectByPrimaryKey(Integer subjectno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject
     *
     * @mbggenerated Sat Jan 13 15:50:48 CST 2018
     */
    int updateByExampleSelective(@Param("record") Subject record, @Param("example") SubjectCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject
     *
     * @mbggenerated Sat Jan 13 15:50:48 CST 2018
     */
    int updateByExample(@Param("record") Subject record, @Param("example") SubjectCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject
     *
     * @mbggenerated Sat Jan 13 15:50:48 CST 2018
     */
    int updateByPrimaryKeySelective(Subject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject
     *
     * @mbggenerated Sat Jan 13 15:50:48 CST 2018
     */
    int updateByPrimaryKey(Subject record);
}